[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "dark"
primaryColor = "#00ff88"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"

[browser]
gatherUsageStats = false
